# Dev Profile

# Database
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/zen_dev}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:jgbs2201}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/liquibase/master.xml

# Logging
logging.level.com.mentorzen=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.liquibase=INFO

# DevTools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# Security - Apenas local, não usar em produção
jwt.secret=${JWT_SECRET:jwt}
